### ISSUE TITLE
Zotero crashes when interacting with Google Docs

### ISSUE THREAD

**Issue by gacrestani** [flathub/org.zotero.Zotero#207]
Hello Flatpak team!

After the update, the Zotero client unexpectedly closes when I use the Google Docs integration. Any task I do (Add/Edit Citation, Refresh, Unlink, etc) causes my Zotero client to close (without any error warnings), while my Google Docs document gets frozen with the "Zotero is updating your document. Please wait..." message (which only goes away if I refresh the page). Note that saving a paper to Zotero works well, apparently the problem is particularly associated with Google Docs.

My browser is Firefox with a freshly reinstalled Zotero Connector extension. I run Zotero as a Flatpak downloaded from Flathub in Fedora Silverblue 40.

Is anyone else having this issue? I reinstalled Zotero and used another browser with no success.

**Comment by carlocastoldi** [comment]
This was fixed with the latest release, downloadable from the official website. I think it is from August 15.

**Comment by carlocastoldi** [comment]
@sebastian-de could you please merge https://github.com/flathub/org.zotero.Zotero/pull/210?

Thank you!

**Comment by gacrestani** [comment]
I reinstalled the flatpak and it still crashes when interacting with Google Docs.

**Comment by sebastian-de** [comment]
> @sebastian-de could you please merge #210?

The flatpak is now version 7.0.3, can you check if the problem persists? But I guess this is a duplicate of #165 anyway.

**Comment by gacrestani** [comment]
> > @sebastian-de could you please merge #210?
> 
> The flatpak is now version 7.0.3, can you check if the problem persists? But I guess this is a duplicate of #165 anyway.

After deleting all Zotero-related folders I could find and the browser extension, I reinstalled the flatpak. It is still crashing.
The error message I get is: ```/app/bin/zotero: line 20:     5 Segmentation fault      (core dumped) "$CALLDIR/zotero-bin" -app "$CALLDIR/app/application.ini" "$@"```

**Comment by sebastian-de** [comment]
Then it's indeed a dupe of #165
